Update README.md
huseyinbagana/ReviewTestRepo pull request #1
Opened 2022-02-12 15:19 UTC by huseyinbagana

2022-02-12 15:37 UTC, tttttsdtsdf requested changes

2022-02-12 15:37 UTC, tttttsdtsdf commented on README.md
> +Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus congue mauris interdum velit rutrum, id pellentesque dolor iaculis. Mauris lacus nisi, pharetra id congue sed, ultricies ut justo. Qui
please remove that line

2022-02-12 15:37 UTC, tttttsdtsdf commented on README.md
> +Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus congue mauris interdum velit rutrum, id pellentesque dolor iaculis. Mauris lacus nisi, pharetra id congue sed, ultricies ut justo. Qui
reply that

2022-02-12 15:37 UTC, tttttsdtsdf commented on README.md
> +Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus congue mauris interdum velit rutrum, id pellentesque dolor iaculis. Mauris lacus nisi, pharetra id congue sed, ultricies ut justo. Qui
```suggestion
you can use that paragraph
```

2022-02-12 15:37 UTC, tttttsdtsdf commented on README.md
> +Donec consectetur facilisis vestibulum. Cras leo lectus, elementum sit amet lacinia imperdiet, varius et erat. Ut convallis nulla posuere justo sodales, vitae volutpat orci luctus. Maecenas ac dictum
- [ ] sdfdfgdfgdfgfdg

2022-02-26 10:13 UTC, huseyinbagana reviewed
- [x] Do this and this
- [x] another thing

2022-02-26 10:15 UTC, huseyinbagana commented on README.md
> +
asdasd

- [ ]

2022-02-26 10:15 UTC, huseyinbagana commented on README.md
> +
```suggestion
`thake this as a sug`
```

2022-04-24 05:25 UTC, closed without merging